name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - run: npm install
      - run: npx cap add android
      - run: npx cap sync
      - run: cd android && ./gradlew assembleRelease
      - run: tree android/app/build

      - uses: actions/upload-artifact@v4
        with: 
          name: problems-report.html
          path: android/build/reports/problems/problems-report.html
        
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        
