name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - run: npm install
      - run: npx cap add android
      - run: npx cap sync
      # - run: cd android && ./gradlew assembleRelease
      #   env:
      #       STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      #       KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      #       KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release.apk
      #     path: android/app/build/outputs/apk/release/*.apk

      - run: cd android && ./gradlew assembleDebug
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/debug/*.apk
          
      - run: tree android/app/build

      - uses: actions/upload-artifact@v4
        with: 
          name: problems-report.html
          path: android/build/reports/problems/problems-report.html

      
        
