name: Build Android APK
on: 
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - run: npm install
      - run: npx cap sync || echo "Capacitor sync failed"
      - run: ls -la android # Debug: Verify Android directory
      - run: ls -la android/app # Debug: Verify app directory
      - run: cd android && ./gradlew assembleRelease --stacktrace --info || echo "Build failed"
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - run: ls -la android/app # Debug: Check for build directory
      - run: tree android/app/build || echo "Build directory not found"
      - run: find android -name "*.apk" || echo "No APKs found"
      
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
